### ISSUE TITLE
UNPREDICTABLE_GAS_LIMIT when running `ccns-register` 

### ISSUE THREAD

**Issue by Throvn** [smartcontractkit/ccip-cross-chain-name-service#1]
```shell
$ npx hardhat ccns-register --ccns-name hello.ccns

ℹ️  Attempting to call the register function on the CrossChainNameServiceRegister smart contract with the name hello.ccns on the ethereumGoerli blockchain
\An unexpected error occurred:

Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x7bec45cd724dc5BCCC5CB1AF6caEd0d4Fe309Fb0","to":"0xc317B308122e4bEc87aEF74682480db51107d36A","data":"0xf2c298be0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000a68656c6c6f2e63636e7300000000000000000000000000000000000000000000","accessList":null}, error={"name":"ProviderError","_stack":"ProviderError: execution reverted\n    at HttpProvider.request (/Users/throvn/Documents/ccip-cross-chain-name-service/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async EthersProviderWrapper.send (/Users/throvn/Documents/ccip-cross-chain-name-service/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)","code":-32000,"_isProviderError":true}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (/Users/throvn/Documents/ccip-cross-chain-name-service/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/throvn/Documents/ccip-cross-chain-name-service/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at checkError (/Users/throvn/Documents/ccip-cross-chain-name-service/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:78:20)
    at EthersProviderWrapper.<anonymous> (/Users/throvn/Documents/ccip-cross-chain-name-service/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:642:20)
    at step (/Users/throvn/Documents/ccip-cross-chain-name-service/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/throvn/Documents/ccip-cross-chain-name-service/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/throvn/Documents/ccip-cross-chain-name-service/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'execution reverted',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  method: 'estimateGas',
  transaction: {
    from: '0x7bec45cd724dc5BCCC5CB1AF6caEd0d4Fe309Fb0',
    to: '0xc317B308122e4bEc87aEF74682480db51107d36A',
    data: '0xf2c298be0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000a68656c6c6f2e63636e7300000000000000000000000000000000000000000000',
    accessList: null
  },
  error: ProviderError: execution reverted
      at HttpProvider.request (/Users/throvn/Documents/ccip-cross-chain-name-service/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async EthersProviderWrapper.send (/Users/throvn/Documents/ccip-cross-chain-name-service/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
}
```

This error happens when trying to run the example. The contracts are all unchanged, I only changed from `ethereumSepolia` to `ethereumGoerli`.
Can someone reproduce this? Or do I actually have to set a gas limit?

**Comment by pinnpin** [comment]
Hey!

Seems like you are trying to use Ethereum Goerli. Right now, Ethereum Goerli is not a network supported by CCIP.

Check the official CCIP documentation to keep track of the Supported Networks: https://docs.chain.link/ccip/supported-networks
